### ISSUE TITLE
Infinite ammo/firing

### ISSUE THREAD

**Issue by RunoHawk** [maltiez2/vsmod_firearms#3]
After firing, as long as you keep holding aim button (RMB) you can switch to different hotbar slot, change it back to firearm and shoot another bullet without need to reload. Also after switching back to the firearm you can release the RMB and it's once again loaded.

https://github.com/maltiez2/vsmod_firearms/assets/39589368/4e16e44e-fcae-4db6-b60f-89d8da09e6ac

**Comment by maltiez2** [comment]
Thanks for report, sorry for long answer. Fixed this bug, just need to build for .NET 4.6 and make an release.
